spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olmago_order
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.kafka.bootstrap-servers: 127.0.0.1:9093

spring.cloud.stream:
  defaultBinder: kafka

  kafka:
    binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9093
      replication-factor: 1

  default.contentType: application/json

  bindings:
    contract-command-0:
      destination: contract-command-topic
      producer:
        required-groups: auditGroup