spring:
  config:
    activate:
      on-profile: db-dev

  datasource:
    url: jdbc:mysql://localhost:3306/olmago_order
    username: olmago
    password: olmago
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQL57Dialect
