server.port: 8083
server.error.include-message: always

logging:
  level:
    root: INFO
    team.caltech.olmago.order.domain: DEBUG
    com:
      querydsl:
        sql: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: DEBUG
