spring:
  config:
    activate:
      on-profile: db-local

  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/order;
    username: sa
    password: 
  #data: classpath:data.sql
  #initialization-mode: always        spring 2.5??? ?? ??? data.sql ????.