server.port: 80
server.error.include-message: always

logging:
  level:
    root: INFO
    team.caltech.olmago.order.domain: INFO
    com:
      querydsl:
        sql: INFO
    org:
      hibernate:
        SQL: INFO
        type: INFO
