spring.profiles.group:
  "local": "kafka-dev,db-local,app-dev"
  "dev": "kafka-dev,db-dev,app-dev"
  "prod": "kafka-prod,db-prod,app-prod"

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json

spring.cloud.function:
  definition: functionRouter
  routing-expression: headers['message-name']

  bindings:
    functionRouter-in-0:
      destination: contract-event-topic
      group: order-group
      consumer:
        maxAttempts: 3
        backOffInitialInterval: 500
        backOffMaxInterval: 1000
        backOffMultiplier: 2.0