docker run -it mysql:5.7 mysql

alter database olmago_order default character set utf8;

drop table if exists message_in_box CASCADE ;
drop table if exists msg_envelope CASCADE ;
drop table if exists ord CASCADE ;
drop table if exists ord_dtl CASCADE;

create table message_in_box (
   id varchar(255) not null,
    event_type varchar(255) not null,
    payload varchar(255) not null,
    received_date_time datetime(6) not null,
    primary key (id)
) engine=InnoDB;


create table msg_envelope (
   id bigint not null auto_increment,
    agg_id varchar(255) not null,
    agg_typ varchar(255) not null,
    bind_nm varchar(255) not null,
    created_at datetime(6) not null,
    event_typ varchar(255) not null,
    payload varchar(2048) not null,
    published boolean not null,
    published_at datetime(6),
    uuid varchar(255) not null,
    primary key (id)
) engine=InnoDB;


create table ord (
   id bigint generated by default as identity,
    cust_id bigint not null,
    ord_cncl_dtm datetime(6),
    ord_cmpl_dtm datetime(6),
    ord_rcv_dtm datetime(6) not null,
    ord_typ varchar(30) not null,
    pay_id bigint,
    version integer not null,
    primary key (id)
) engine=InnoDB;

create table ord_dtl (
   id bigint generated by default as identity,
    contract_id bigint,
    contract_type varchar(10),
    product_code varchar(10),
    version integer not null,
    order_id bigint,
    primary key (id)
) engine=InnoDB;

create index message_envelope_n1 on msg_envelope (published, id);

alter table ord_dtl
   add constraint ord_dtl_fk_ord_id
   foreign key (order_id)
   references ord;